language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
- sudo apt-get install -y wkhtmltopdf
- sudo apt-get install -y graphviz
- mkdir -p output
script:
- python report.py --excel
deploy:
  provider: releases
  api_key:
    secure: egMsjlsQ0nP3pOxePWS2y992ngncBH9n36CaDyPillttPV3QImc+CkSHZLSaE98n5OesYyUPAgD8k/LPDQV/QF6miPN4N6dlD82BBsw4GMxeHBkETeTIKQUTK4mgbj0tw9a6V7vxurNeqxzZy3WBaWXTh7s8n31K7f196S46VjJkjvghpuR4m3j4KbBifiQVDx9IHltR2UUkpkaDkGelPdH2TkGw2ac93qL3aICURe7VF8AUcEnsL9bWZ7aFEwPpc9XrvylQVI1yiE4iTpKvoovWN6xJEPKLOdh9OtTQh7BVxdTIgokNbnoeCf5yZtKCXCljhAq83rZeEQDQAL1y2RCDGrW8osF8dgUoanyfAKrKn0TdvKfE7R+Halyg2YO8smBrSwwbJYfmyh0EJ+PCTmZznq7CzdReh1hDSv0HXePWJ5P71v+3+uko1TqQWb8MxEcgJa84zaH4rQ5RsAHKXlQoObxSVnzY5e0qPfLyQ78HLa56j+3O8JJnQJY6lu4EcZKif68fJWypkhTRVMcoOfBf1wWxiSGZ/1L8BFR8jPAFOybQwXX4oQ7CTKE3KsZToVR2m6E4Y3EjBP5TwniqwDkb63nW6hifw9fHgqaNBUWHNQejCwcp6VjE3rMIMzhXhx9UzCNMeF4u4PjtAdygeALiBWe2Tx45yPIpOBFuKBk=
  file: output/report.xlsx
  on:
    tags: true
    repo: tidepool-org/reports
    branch: main
