# these come from either .env or environment
# base_url: https://tidepool.atlassian.net
# username: travis-ci@tidepool.org
# api_token: ...
filters:
  junk_resolution: [ 'Duplicate', "Won't Do", 'Deprecated', 'Cannot Reproduce', 'As Designed' ]
  done_status: [ 'Waiting for Approval', 'Waiting for Deployment', 'Closed' ]
  blocked_status: [ 'Blocked' ]
  device_qual_component: [ 'Device Qualification' ]
parameters:
  fix_version: 'FDA 510(k) Sub' # used in exclude_junk filter as well
  fix_version_risks: 'SOP-006 v7'
  component_criteria: '(component IN (iAGC) OR component IS EMPTY OR component NOT IN (ExcludeFromReport, "iOS Compatibility"))'
  component_criteria_bugs: '(component IN (iAGC) AND component NOT IN (ExcludeFromReport, "iOS Compatibility"))'
queries:
  func_requirements: project=TLFR AND issuetype="Functional Requirement" AND status IN ("Dev Ready", Active) AND {component_criteria}
  user_requirements: project=TLFR AND issuetype="User Requirement" AND {component_criteria}
  risks: project=TLR AND (fixVersion="{fix_version_risks}" OR fixVersion IS EMPTY) AND issuetype IN (Story, Task) AND {component_criteria}
  epics: project=LOOP AND fixVersion="{fix_version}" AND issuetype IN (Epic) AND {component_criteria}
  stories: project=LOOP AND fixVersion="{fix_version}" AND issuetype IN (Story, Task, Sub-task) AND {component_criteria}
  bugs: project=LOOP AND issuetype IN (Bug) AND resolution=Unresolved AND {component_criteria_bugs}
  tests: project=LOOP AND issuetype IN (Test, "Test Execution", "Sub Test Execution") AND {component_criteria}
  instructions: project=IFU AND {component_criteria}
fields:
  epic_key: customfield_10014 # "Epic Link"
  functional_requirements: customfield_10132 # "Functional Requirements"
  done_criteria: customfield_10072 # "Done Criteria"
  test_strategy: customfield_10036 # "Test Strategy"
  old_reference_id: customfield_10140 # "OLD Reference ID" - being deprecated
  reference_id: customfield_10165 # "Reference ID"
  source: customfield_10115 # "Source"
  sequence_of_events: customfield_10144 # "Sequence of Events"
  harm: customfield_10089 # SoftComply "Harm"
  hazard: customfield_10090 # SoftComply "Cause"
  hazard_category: customfield_10095 # "Hazard Category"
  initial_severity: customfield_10085 # SoftComply "Severity"
  initial_probability: customfield_10086 # SoftComply "Probability"
  initial_risk: customfield_10101 # SoftComply "Risk (initial)"
  residual_severity: customfield_10093 # SoftComply "Severity (Final)"
  residual_probability: customfield_10094 # SoftComply "Probability (Final)"
  residual_risk: customfield_10102 # SoftComply "Risk (residual)"
  benefit: customfield_10142 # "Requirement ID"
  risk_level: customfield_10027 # "Risk Level"
  uea_level: customfield_10028 # "User Experience Assessment Level"
  reason_for_deferral: customfield_10162 # "Reason for Deferral"
issue_types:
  epic:                { ids: [ 10000 ], projects: [ LOOP, TLR, TLFR, IFU ] }
  story:               { ids: [ 10001, 10002 ], projects: [ LOOP ] }
  subtask:             { ids: [ 10003 ], projects: [ LOOP, TLR, TLFR, IFU ] }
  bug:                 { ids: [ 10004 ], projects: [ LOOP ] }
  feedback:            { ids: [ 10005 ], projects: [ LOOP ] }
  test:                { ids: [ 10016, 10019, 10021, 10017, 10018 ], projects: [ LOOP ] } # Test, Test Execution, Sub Test Execution, Test Set, Test Plan
  func_requirement:    { ids: [ 10024 ], projects: [ TLFR ] }
  user_requirement:    { ids: [ 10027 ], projects: [ TLFR ] }
  risk:                { ids: [ 10001, 10002 ], projects: [ TLR ] } # yes, same as story
  external_mitigation: { ids: [ 10026 ], projects: [ TLR ] }
  instruction:         { ids: [ 10001, 10002 ], projects: [ IFU ] } # yes, same as story
link_types:
  blocks:     { id: 10000 }
  clones:     { id: 10001 }
  duplicates: { id: 10002 }
  relates:    { id: 10003 }
  splits:     { id: 10102 }
  mitigates:  { id: 10103 }
  verifies:   { id: 10104 }
  tests:      { id: 10105 }
  defect:     { id: 10106 }
  changes:    { id: 10107 }
  defines:    { id: 10108 }
cache:
  folder: cache
  refresh: 21600
exclude_fields: [ project, labels, comment, attachment, creator, reporter, assignee, watches, votes, worklog, workratio, progress, aggregateprogress, timetracking, timeestimate, aggregatetimeestimate, aggregatetimeoriginalestimate, timespent, aggregatetimespent, issuerestriction, lastViewed, customfield_10073, customfield_10026, customfield_10021, customfield_10038 ]
